### ISSUE TITLE
bf application, but no gf application

### ISSUE THREAD

**Issue by Rumena-Beloglazova** [Leucean/Leucean.github.io#1]
## Expected Behavior

gf applications in addtion to bf applications

## Actual Behavior

only bf applications

## Steps to Reproduce the Problem

  1. open website
  1. scroll down
  1. observe the lack of a gf applications beside the bf application

## Specifications

  - Version: huh?
  - Platform: my 'puter
  - Subsystem: what this mean?

**Comment by Leucean** [comment]
Fixed! Replace boyfriend with more egalitarian terms!
